# Generated by Django 5.2.10 on 2026-02-14 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactform',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='contactform',
            name='subject',
        ),
    ]
