# Generated by Django 5.2.10 on 2026-02-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_remove_contactform_phone_remove_contactform_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='phone',
            field=models.CharField(default='0', max_length=15),
        ),
    ]
